// This file was autogenerated by /home/ubuntu/Dev/projects/nclosure/third_party/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../../ox/cl/ansiesc.js', ['ox.cl.ansiesc'], []);
goog.addDependency('../../../../../ox/cl/deps.js', [], []);
goog.addDependency('../../../../../ox/cl/editor.js', ['ox.cl.editor'], ['goog.Timer', 'goog.dom', 'goog.events', 'goog.events.Event', 'goog.events.EventTarget', 'goog.style', 'ox.cl.ansiesc']);
goog.addDependency('../../../../../ox/cl/ox.js', ['ox.cl.ox'], ['ox.cl.editor']);
goog.addDependency('../../../../../ox/cl/socket.io.js', [], []);
